version: "1"
rules:
  - base: main
    upstream: CareyWang:master
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - JaimeZeng
    reviewers:
      - JaimeZeng
    conflictReviewers:
      - JaimeZeng
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
